name: Get Data

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.auto-commit-action.outputs.commit_hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Run Python Script
        run: |
          python -m pip install requests
          python -m pip install pytz
          python Writer.py


      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Auto Updated
          file_pattern: ActBlue.csv

# meep
