name: Get Data

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Run Python Script
        run: |
          python -m pip install requests
          python Writer.py

# meep
