name: Get Data

on: 
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.auto-commit-action.outputs.commit_hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Run Writer
        run: |
          python -m pip install requests
          python -m pip install pytz
          python Writer.py


      - name: Commit Changes to CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Auto Updated
          file_pattern: ActBlue.csv

# everything after this comment was added while trying to get the graphs to work. so if everything goes wrong, just delete everything under me

      - name: Run data_cleaning
        run: |
          python -m pip install pandas==2.2.0
          python -m pip install plotly==5.24.0
          python data_cleaning.py


      - name: Commit Changes to Daily
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Auto Updated
          file_pattern: index.html
          

      - name: Commit Changes to Monthly
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Auto Updated
          file_pattern: Monthly_Tracker.html

          

